var annotated_dup =
[
    [ "spdlog", "namespacespdlog.html", null ],
    [ "Assoc", "struct_assoc.html", "struct_assoc" ],
    [ "Block", "class_block.html", "class_block" ],
    [ "blockLess", "structblock_less.html", "structblock_less" ],
    [ "CircularBuffer", "class_circular_buffer.html", "class_circular_buffer" ],
    [ "Client", "class_client.html", "class_client" ],
    [ "CongestionController", "class_congestion_controller.html", "class_congestion_controller" ],
    [ "ConnState", "class_conn_state.html", "class_conn_state" ],
    [ "CTCPCongestionController", "class_c_t_c_p_congestion_controller.html", "class_c_t_c_p_congestion_controller" ],
    [ "CTCPNoDownCongestionController", "class_c_t_c_p_no_down_congestion_controller.html", "class_c_t_c_p_no_down_congestion_controller" ],
    [ "CTCPP2CongestionController", "class_c_t_c_p_p2_congestion_controller.html", "class_c_t_c_p_p2_congestion_controller" ],
    [ "CTCPSDCongestionController", "class_c_t_c_p_s_d_congestion_controller.html", "class_c_t_c_p_s_d_congestion_controller" ],
    [ "Endpoint", "class_endpoint.html", "class_endpoint" ],
    [ "EndpointStats", "struct_endpoint_stats.html", "struct_endpoint_stats" ],
    [ "NonBlockingWriteRequest", "class_non_blocking_write_request.html", "class_non_blocking_write_request" ],
    [ "P2", "class_p2.html", "class_p2" ],
    [ "ringBufferType", "structring_buffer_type.html", "structring_buffer_type" ],
    [ "rlnc_decoder", "classrlnc__decoder.html", "classrlnc__decoder" ],
    [ "rlnc_encoder", "classrlnc__encoder.html", "classrlnc__encoder" ],
    [ "RTTBi5CongestionController", "class_r_t_t_bi5_congestion_controller.html", "class_r_t_t_bi5_congestion_controller" ],
    [ "RTTBiCongestionController", "class_r_t_t_bi_congestion_controller.html", "class_r_t_t_bi_congestion_controller" ],
    [ "RTTBiNCongestionController", "class_r_t_t_bi_n_congestion_controller.html", "class_r_t_t_bi_n_congestion_controller" ],
    [ "RTTBiP2CongestionController", "class_r_t_t_bi_p2_congestion_controller.html", "class_r_t_t_bi_p2_congestion_controller" ],
    [ "RTTDiffCongestionController", "class_r_t_t_diff_congestion_controller.html", "class_r_t_t_diff_congestion_controller" ],
    [ "SendPeerStats", "struct_send_peer_stats.html", "struct_send_peer_stats" ],
    [ "SentRecord", "struct_sent_record.html", "struct_sent_record" ],
    [ "Server", "class_server.html", "class_server" ]
];